/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Servis ve veritabanı durumu */
        get: operations["saglik_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personel listesi */
        get: operations["listele_api_staff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/{staff_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personel künyesi */
        get: operations["getir_api_staff__staff_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** E-09 çizelge ızgarası */
        get: operations["cizelge_api_drafts__draft_id__schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}/cells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Hücreye elle müdahale
         * @description Elle yazılan hücre source='manuel', is_locked=TRUE olur: solver dokunmaz.
         *
         *     Kural uyarıları ENGELLEMEZ. Sorumlu hemşire gerçekliği bildiğinde çizelgeye
         *     yazabilmeli; sistem yalnız neyin ihlal edildiğini söyler (E-09 kararı).
         */
        put: operations["hucre_yaz_api_drafts__draft_id__cells_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Taslak listesi */
        get: operations["listele_api_drafts_get"];
        put?: never;
        /** Yeni taslak */
        post: operations["olustur_api_drafts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Taslak detayı */
        get: operations["getir_api_drafts__draft_id__get"];
        put?: never;
        post?: never;
        /**
         * Taslağı sil
         * @description Atamalar, koşular ve teşhisler de gider (şemadaki ON DELETE CASCADE).
         */
        delete: operations["taslak_sil_api_drafts__draft_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Çöz — arka planda çalıştırır */
        post: operations["coz_api_drafts__draft_id__solve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Taslağın koşuları */
        get: operations["kosular_api_drafts__draft_id__runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solver-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Koşu durumu (yoklama) */
        get: operations["kosu_api_solver_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solver-runs/{run_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** E-10 teşhisler, kurala göre gruplu */
        get: operations["teshisler_api_solver_runs__run_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Taslağı kopyala */
        post: operations["taslak_kopyala_api_drafts__draft_id__copy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Taslağı yayınla */
        post: operations["taslak_yayinla_api_drafts__draft_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ana sayfa kartı */
        get: operations["ozet_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Haftalık ihtiyaç görünümü */
        get: operations["haftalik_api_demand_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/need-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** İhtiyaç şablonu */
        get: operations["sablon_api_need_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/need-template-rows/{row_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Şablon satırını sil */
        delete: operations["satir_sil_api_need_template_rows__row_id__delete"];
        options?: never;
        head?: never;
        /** Şablon satırının kişi sayısını değiştir */
        patch: operations["satir_guncelle_api_need_template_rows__row_id__patch"];
        trace?: never;
    };
    "/api/need-templates/{template_id}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Şablona satır ekle */
        post: operations["satir_ekle_api_need_templates__template_id__rows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personel listesi */
        get: operations["listele_api_people_get"];
        put?: never;
        /** Personel ekle */
        post: operations["olustur_api_people_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rol listesi */
        get: operations["roller_api_people_roles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{staff_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personel detayı */
        get: operations["detay_api_people__staff_id__get"];
        put?: never;
        post?: never;
        /**
         * Personeli sil veya pasife al
         * @description Ataması olan personel silinmez, pasife alınır.
         *
         *     Veritabanı da buna zorluyor (fk_assignments_staff RESTRICT): geçmiş çizelgeler
         *     korunmalı. Pasif kişi listelerden ve solver'dan düşer ama kaydı durur.
         */
        delete: operations["sil_api_people__staff_id__delete"];
        options?: never;
        head?: never;
        /** Personel düzenle */
        patch: operations["guncelle_api_people__staff_id__patch"];
        trace?: never;
    };
    "/api/people/{staff_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pasif personeli aktife al */
        post: operations["aktife_al_api_people__staff_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{staff_id}/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sözleşme ekle */
        post: operations["sozlesme_ekle_api_people__staff_id__contracts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{staff_id}/absences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Devamsızlık ekle */
        post: operations["izin_ekle_api_people__staff_id__absences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{staff_id}/absences/{absence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Devamsızlık sil */
        delete: operations["izin_sil_api_people__staff_id__absences__absence_id__delete"];
        options?: never;
        head?: never;
        /** Devamsızlık düzenle */
        patch: operations["izin_guncelle_api_people__staff_id__absences__absence_id__patch"];
        trace?: never;
    };
    "/api/people/{staff_id}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Müsaitlik kuralı ekle */
        post: operations["musaitlik_ekle_api_people__staff_id__availability_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{staff_id}/availability/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Müsaitlik kuralı sil */
        delete: operations["musaitlik_sil_api_people__staff_id__availability__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{staff_id}/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Uyumsuz kişi ekle */
        post: operations["uyumsuzluk_ekle_api_people__staff_id__conflicts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{staff_id}/conflicts/{other_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Uyumsuz kişi sil */
        delete: operations["uyumsuzluk_sil_api_people__staff_id__conflicts__other_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{staff_id}/contracts/{contract_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sözleşme sil */
        delete: operations["sozlesme_sil_api_people__staff_id__contracts__contract_id__delete"];
        options?: never;
        head?: never;
        /** Sözleşme düzenle */
        patch: operations["sozlesme_guncelle_api_people__staff_id__contracts__contract_id__patch"];
        trace?: never;
    };
    "/api/competencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yetkinlik listesi */
        get: operations["yetkinlikler_api_competencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/competency-matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** E-02 matrisi */
        get: operations["matris_api_competency_matrix_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/people/{staff_id}/competencies/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Yetkinlik kutucuğunu aç/kapa */
        put: operations["yetkinlik_degistir_api_people__staff_id__competencies__code__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kural seti */
        get: operations["kurallar_api_constraints_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constraints/{constraint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Kuralı düzenle */
        patch: operations["kural_guncelle_api_constraints__constraint_id__patch"];
        trace?: never;
    };
    "/api/constraint-params/{param_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Kural parametresini düzenle */
        patch: operations["param_guncelle_api_constraint_params__param_id__patch"];
        trace?: never;
    };
    "/api/shift-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vardiya tanımları */
        get: operations["vardiyalar_api_shift_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Absence */
        Absence: {
            /** Id */
            id: number;
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             * @description DAHİL
             */
            end: string;
            /**
             * Absence Type
             * @enum {string}
             */
            absence_type: "yillik_izin" | "rapor" | "ucretsiz_izin" | "diger";
            /** Type Label */
            type_label: string;
            /** Note */
            note?: string | null;
        };
        /** AbsenceCreate */
        AbsenceCreate: {
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             * @description DAHİL
             */
            end: string;
            /**
             * Absence Type
             * @enum {string}
             */
            absence_type: "yillik_izin" | "rapor" | "ucretsiz_izin" | "diger";
            /** Note */
            note?: string | null;
        };
        /** AvailabilityCreate */
        AvailabilityCreate: {
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Rule Type
             * @enum {string}
             */
            rule_type: "off_talebi" | "acilis_tercihi" | "kapanis_tercihi";
            /** Note */
            note?: string | null;
        };
        /** AvailabilityRule */
        AvailabilityRule: {
            /** Id */
            id: number;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /**
             * Rule Type
             * @enum {string}
             */
            rule_type: "off_talebi" | "acilis_tercihi" | "kapanis_tercihi";
            /** Type Label */
            type_label: string;
            /** Note */
            note?: string | null;
        };
        /**
         * Cell
         * @description Bir kişinin bir günü. Vardiya yoksa hücre hiç gönderilmez.
         */
        Cell: {
            /** Shift Code */
            shift_code: string;
            /**
             * Shift Label
             * @enum {string}
             */
            shift_label: "G" | "N";
            /**
             * Tasks
             * @description Görev kodları: TRIYAJ, AMBULANS, GOZLEM
             */
            tasks?: string[];
            /**
             * Is Locked
             * @default false
             */
            is_locked: boolean;
            /** Source */
            source: string;
        };
        /** CellResult */
        CellResult: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /**
             * Warnings
             * @description Kural uyarıları. Engellemez — elle müdahale gerçeği kaydeder (E-09 kararı).
             */
            warnings?: string[];
        };
        /**
         * CellUpdate
         * @description Izgara hücresine elle müdahale (E-09 taslak içi).
         */
        CellUpdate: {
            /** Staff Id */
            staff_id: number;
            /**
             * Work Date
             * Format: date
             */
            work_date: string;
            /**
             * Shift Code
             * @description IZIN bir devamsızlık kaydı yazar; BOS atamayı siler
             * @enum {string}
             */
            shift_code: "GUNDUZ" | "GECE" | "IZIN" | "BOS";
            /**
             * Tasks
             * @description TRIYAJ / GOZLEM / AMBULANS
             */
            tasks?: string[];
        };
        /** Competency */
        Competency: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "TASK" | "QUALIFICATION";
            /** Description */
            description?: string | null;
            /**
             * Staff Count
             * @description Sütun altı toplamı — fizibilite erken görünsün
             * @default 0
             */
            staff_count: number;
        };
        /** CompetencyMatrix */
        CompetencyMatrix: {
            /** Tasks */
            tasks: components["schemas"]["Competency"][];
            /** Qualifications */
            qualifications: components["schemas"]["Competency"][];
            /** Rows */
            rows: components["schemas"]["MatrixRow"][];
        };
        /** Conflict */
        Conflict: {
            /** Other Staff Id */
            other_staff_id: number;
            /** Other Name */
            other_name: string;
            /** Note */
            note?: string | null;
        };
        /** ConflictCreate */
        ConflictCreate: {
            /** Other Staff Id */
            other_staff_id: number;
            /** Note */
            note?: string | null;
        };
        /** Constraint */
        Constraint: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Catalog Code */
            catalog_code?: string | null;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Is Hard */
            is_hard: boolean;
            /**
             * Default Weight
             * @description Soft kuralda pozitif, hard'da boş
             */
            default_weight?: number | null;
            /** Scope */
            scope: string;
            /** Scope Label */
            scope_label: string;
            /** Source */
            source: string;
            /** Source Label */
            source_label: string;
            /**
             * Locked
             * @description Kaynağı 'yasal' olanlar gevşetilemez
             */
            locked: boolean;
            /** Params */
            params?: components["schemas"]["ConstraintParam"][];
        };
        /** ConstraintParam */
        ConstraintParam: {
            /** Id */
            id: number;
            /** Param Key */
            param_key: string;
            /** Param Value */
            param_value: number;
            /** Description */
            description?: string | null;
        };
        /** ConstraintUpdate */
        ConstraintUpdate: {
            /** Is Hard */
            is_hard?: boolean | null;
            /** Default Weight */
            default_weight?: number | null;
        };
        /** Contract */
        Contract: {
            /** Id */
            id: number;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /**
             * Valid To
             * @description Açık uçluysa boş
             */
            valid_to?: string | null;
            /**
             * Monthly Target Hours
             * @description Boşsa kural varsayılanı (monthly_min_hours) geçerli
             */
            monthly_target_hours?: number | null;
            /** Note */
            note?: string | null;
        };
        /** ContractUpsert */
        ContractUpsert: {
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to?: string | null;
            /** Monthly Target Hours */
            monthly_target_hours?: number | null;
            /** Note */
            note?: string | null;
        };
        /** DayHeader */
        DayHeader: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /**
             * Weekday
             * @description Pzt, Sal, …
             */
            weekday: string;
            /**
             * Label
             * @description Gün + kısa ay, örn. '21 Eyl'
             */
            label: string;
            /** Is Weekend */
            is_weekend: boolean;
            /** Shifts */
            shifts: components["schemas"]["ShiftHeader"][];
        };
        /**
         * DeleteResult
         * @description Silme mi oldu, pasife mi alındı — arayüz doğru mesajı gösterebilsin.
         */
        DeleteResult: {
            /** Deleted */
            deleted: boolean;
            /** Deactivated */
            deactivated: boolean;
            /** Message */
            message: string;
        };
        /** Demand */
        Demand: {
            /** Period Label */
            period_label: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             * @description DIŞLAYICI
             */
            period_end: string;
            draft?: components["schemas"]["DemandDraft"] | null;
            total: components["schemas"]["DemandTotal"];
            /**
             * Days
             * @description Çizelgeyle aynı yapı — tek tanım, tek davranış
             */
            days: components["schemas"]["DayHeader"][];
        };
        /** DemandDraft */
        DemandDraft: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Is Published */
            is_published: boolean;
            /**
             * Is Reference Copy
             * @default false
             */
            is_reference_copy: boolean;
        };
        /** DemandTotal */
        DemandTotal: {
            /**
             * Required Hours
             * @description Minimum kadro saati: GENEL min_count × vardiya süresi
             */
            required_hours: number;
            /** Assigned Hours */
            assigned_hours: number;
            /** Shortfall Count */
            shortfall_count: number;
        };
        /** Diagnostic */
        Diagnostic: {
            /** Id */
            id: number;
            /**
             * Severity
             * @enum {string}
             */
            severity: "cakisma" | "ihlal" | "uyari";
            /** Constraint Code */
            constraint_code?: string | null;
            /** Catalog Code */
            catalog_code?: string | null;
            /** Constraint Name */
            constraint_name?: string | null;
            /** Staff Name */
            staff_name?: string | null;
            /** Work Date */
            work_date?: string | null;
            /** Message */
            message: string;
            /** Suggestion */
            suggestion?: string | null;
        };
        /**
         * DiagnosticGroup
         * @description E-10: teşhisler kurala göre gruplanır — 44 satır yerine 7 kalem.
         */
        DiagnosticGroup: {
            /** Catalog Code */
            catalog_code?: string | null;
            /** Constraint Code */
            constraint_code?: string | null;
            /** Constraint Name */
            constraint_name: string;
            /** Count */
            count: number;
            /** First Date */
            first_date?: string | null;
            /** Last Date */
            last_date?: string | null;
            /**
             * Samples
             * @description İlk birkaç örnek
             */
            samples?: components["schemas"]["Diagnostic"][];
        };
        /** Draft */
        Draft: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             * @description DIŞLAYICI bitiş: [başlangıç, bitiş)
             */
            period_end: string;
            /**
             * Day Count
             * @description Aralıktaki gün sayısı
             * @default 0
             */
            day_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "taslak" | "yayinlandi" | "arsiv";
            /** Unit Name */
            unit_name: string;
            /** Created At */
            created_at?: string | null;
            /** Published At */
            published_at?: string | null;
            /**
             * Assignment Count
             * @default 0
             */
            assignment_count: number;
            /**
             * Staff Count
             * @description Ataması olan kişi sayısı
             * @default 0
             */
            staff_count: number;
            /**
             * Shortfall Count
             * @description Kapsama eksiği olan slot sayısı
             * @default 0
             */
            shortfall_count: number;
            /**
             * Total Hours
             * @default 0
             */
            total_hours: number;
            /**
             * Overtime Hours
             * @default 0
             */
            overtime_hours: number;
            /**
             * Fairness Gap
             * @description En çok − en az çalışan saat farkı
             * @default 0
             */
            fairness_gap: number;
            /**
             * Covers Full Month
             * @default false
             */
            covers_full_month: boolean;
            last_run?: components["schemas"]["SolverRun"] | null;
        };
        /** DraftCopy */
        DraftCopy: {
            /** Name */
            name: string;
        };
        /** DraftCreate */
        DraftCreate: {
            /**
             * Period Start
             * Format: date
             * @description Başlangıç günü (dahil)
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             * @description Bitiş günü (DAHİL) — API dışlayıcıya çevirir
             */
            period_end: string;
            /** Name */
            name: string;
            /**
             * Unit Code
             * @default ACIL_SERVIS
             */
            unit_code: string;
            /**
             * Seed From
             * @default bos
             * @enum {string}
             */
            seed_from: "bos" | "yayinlanmis" | "referans";
            /**
             * Lock Seeded
             * @description Kopyalanan atamalar kilitlensin (solver dokunmaz)
             * @default false
             */
            lock_seeded: boolean;
        };
        /** DraftInfo */
        DraftInfo: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             * @description DIŞLAYICI bitiş: [başlangıç, bitiş)
             */
            period_end: string;
            /** Status */
            status: string;
            /** Unit Name */
            unit_name: string;
            /**
             * Covers Full Month
             * @description Taslağın aralığı tam bir takvim ayı mı VE atamalar o aralığı kapsıyor mu? Aylık hedef (C-004) yalnızca bu doğruysa anlamlıdır.
             */
            covers_full_month: boolean;
        };
        /**
         * Group
         * @description DESIGN §6: rol grubuna göre katlanabilir bölümler.
         */
        Group: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Rows */
            rows: components["schemas"]["Row"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheck */
        HealthCheck: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "hata";
            /** Db */
            db: boolean;
            /** Tablo */
            tablo?: number | null;
            /** View */
            view?: number | null;
            /** Aktif Personel */
            aktif_personel?: number | null;
            /**
             * Sema Guncel
             * @description Veritabanı şeması deploy edilen kodun beklediği migration'ları içeriyor mu
             */
            sema_guncel?: boolean | null;
            /**
             * Eksik Migration
             * @description Veritabanında eksik olan migration'lar
             */
            eksik_migration?: string | null;
            /** Detay */
            detay?: string | null;
        };
        /** MatrixRow */
        MatrixRow: {
            /** Staff Id */
            staff_id: number;
            /** Full Name */
            full_name: string;
            /** Role Name */
            role_name: string;
            /** Is Orientation */
            is_orientation: boolean;
            /**
             * Codes
             * @description Sahip olduğu yetkinlik kodları
             */
            codes?: string[];
        };
        /** NeedTemplate */
        NeedTemplate: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Rows */
            rows: components["schemas"]["TemplateRow"][];
        };
        /** Overview */
        Overview: {
            /** Unit Name */
            unit_name: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             * @description DIŞLAYICI bitiş
             */
            period_end: string;
            /** Period Label */
            period_label: string;
            draft?: components["schemas"]["OverviewDraft"] | null;
            /**
             * Assigned Hours
             * @description Dönemdeki atamaların toplam planlanan saati
             */
            assigned_hours: number;
            /**
             * Required Hours
             * @description İhtiyaç şablonundan türetilen gereken saat: her gün, her vardiya için GENEL min_count × vardiya süresi
             */
            required_hours: number;
            /**
             * Coverage Ratio
             * @description assigned / required, 0 ise 0
             */
            coverage_ratio: number;
            /**
             * Violation Count
             * @description Kapsama eksiği olan gün-vardiya-slot sayısı
             */
            violation_count: number;
            /**
             * Violation Label
             * @description Stub'da 'Kapsama eksiği', gerçek çözümde 'Kural ihlali'
             */
            violation_label: string;
            /** Overtime Hours */
            overtime_hours?: number | null;
            /**
             * Fairness Gap
             * @description En çok − en az çalışan saat farkı
             */
            fairness_gap?: number | null;
        };
        /** OverviewDraft */
        OverviewDraft: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Is Published
             * @description Yayınlanmış mı, yoksa yalnızca taslak mı
             */
            is_published: boolean;
            /**
             * Is Reference Copy
             * @description Son çalıştırma stub mı? Diğer ekranlardaki etiketlerle tutarlı olsun diye.
             * @default false
             */
            is_reference_copy: boolean;
        };
        /** ParamUpdate */
        ParamUpdate: {
            /** Param Value */
            param_value: number;
        };
        /** PersonCreate */
        PersonCreate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Role Code */
            role_code: string;
            /**
             * Shift Eligibility
             * @default gunduz_gece
             * @enum {string}
             */
            shift_eligibility: "gunduz_gece" | "sadece_gunduz" | "sadece_gece";
            /** Sicil No */
            sicil_no?: string | null;
            /** Seniority Years */
            seniority_years?: number | null;
            /** Note */
            note?: string | null;
        };
        /** PersonDetail */
        PersonDetail: {
            /** Id */
            id: number;
            /**
             * Sicil No
             * @description Boşsa boş gösterilir, uydurulmaz
             */
            sicil_no?: string | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Full Name */
            full_name: string;
            /** Role Code */
            role_code: string;
            /** Role Name */
            role_name: string;
            /**
             * Shift Eligibility
             * @enum {string}
             */
            shift_eligibility: "gunduz_gece" | "sadece_gunduz" | "sadece_gece";
            /** Eligibility Label */
            eligibility_label: string;
            /**
             * Monthly Target Hours
             * @description Etkin aylık hedef: sözleşmedeki değer, yoksa kural varsayılanı
             */
            monthly_target_hours?: number | null;
            /**
             * Target Is Default
             * @description Hedef sözleşmeden değil kuraldan geliyorsa true
             * @default false
             */
            target_is_default: boolean;
            /**
             * Contract Label
             * @description Sözleşme aralığı, insan diliyle
             */
            contract_label?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Is Orientation */
            is_orientation: boolean;
            /** Buddy Name */
            buddy_name?: string | null;
            /**
             * Status Label
             * @description Oryantasyon / Pasif / boş
             */
            status_label: string;
            /** Buddy Staff Id */
            buddy_staff_id?: number | null;
            /**
             * Assignment Count
             * @description Kaç atamada geçiyor — silinebilir mi, pasife mi alınmalı
             * @default 0
             */
            assignment_count: number;
            /**
             * Can Delete
             * @description Ataması yoksa gerçekten silinebilir
             * @default true
             */
            can_delete: boolean;
            /** Seniority Years */
            seniority_years?: number | null;
            /** Note */
            note?: string | null;
            /** Contracts */
            contracts?: components["schemas"]["Contract"][];
            /** Absences */
            absences?: components["schemas"]["Absence"][];
            /** Availability */
            availability?: components["schemas"]["AvailabilityRule"][];
            /** Conflicts */
            conflicts?: components["schemas"]["Conflict"][];
        };
        /**
         * PersonRow
         * @description Liste satırı. Yetkinlik rozeti YOK — o E-02'de (26.09 kararı).
         */
        PersonRow: {
            /** Id */
            id: number;
            /**
             * Sicil No
             * @description Boşsa boş gösterilir, uydurulmaz
             */
            sicil_no?: string | null;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Full Name */
            full_name: string;
            /** Role Code */
            role_code: string;
            /** Role Name */
            role_name: string;
            /**
             * Shift Eligibility
             * @enum {string}
             */
            shift_eligibility: "gunduz_gece" | "sadece_gunduz" | "sadece_gece";
            /** Eligibility Label */
            eligibility_label: string;
            /**
             * Monthly Target Hours
             * @description Etkin aylık hedef: sözleşmedeki değer, yoksa kural varsayılanı
             */
            monthly_target_hours?: number | null;
            /**
             * Target Is Default
             * @description Hedef sözleşmeden değil kuraldan geliyorsa true
             * @default false
             */
            target_is_default: boolean;
            /**
             * Contract Label
             * @description Sözleşme aralığı, insan diliyle
             */
            contract_label?: string | null;
            /** Is Active */
            is_active: boolean;
            /** Is Orientation */
            is_orientation: boolean;
            /** Buddy Name */
            buddy_name?: string | null;
            /**
             * Status Label
             * @description Oryantasyon / Pasif / boş
             */
            status_label: string;
        };
        /** PersonUpdate */
        PersonUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Role Code */
            role_code?: string | null;
            /** Shift Eligibility */
            shift_eligibility?: ("gunduz_gece" | "sadece_gunduz" | "sadece_gece") | null;
            /** Sicil No */
            sicil_no?: string | null;
            /** Seniority Years */
            seniority_years?: number | null;
            /** Note */
            note?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Orientation */
            is_orientation?: boolean | null;
            /**
             * Buddy Staff Id
             * @description Oryantasyondaysa eğitmen. Şema kuralı: oryantasyon → eğitmen zorunlu.
             */
            buddy_staff_id?: number | null;
        };
        /**
         * QualificationFlag
         * @description Tooltip'in alt satırı: 'Ekip lideri ✓' gibi. Sayı değil, var/yok.
         */
        QualificationFlag: {
            /** Label */
            label: string;
            /** Present */
            present: boolean;
        };
        /** Role */
        Role: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** Row */
        Row: {
            /** Staff Id */
            staff_id: number;
            /** Full Name */
            full_name: string;
            /** Role Name */
            role_name: string;
            /** Is Orientation */
            is_orientation: boolean;
            /** Initials */
            initials: string;
            /**
             * Cells
             * @description ISO tarih → hücre; çalışılmayan gün anahtarı yok
             */
            cells: {
                [key: string]: components["schemas"]["Cell"];
            };
            /**
             * Absences
             * @description ISO tarih → izin türü
             */
            absences?: {
                [key: string]: string;
            };
            /**
             * Period Hours
             * @description Taslağın DÖNEMİNDEKİ toplam planlanan saat
             */
            period_hours: number;
            /**
             * Period Target
             * @description Aylık hedefin döneme orantılanmış hali: aylık hedef × dönem gün sayısı / ayın gün sayısı
             */
            period_target: number;
            /**
             * Period Diff
             * @description Hedefe göre fark: pozitif fazla, negatif eksik
             */
            period_diff: number;
            /** Shift Count */
            shift_count: number;
        };
        /** Schedule */
        Schedule: {
            draft: components["schemas"]["DraftInfo"];
            /** Days */
            days: components["schemas"]["DayHeader"][];
            /** Groups */
            groups: components["schemas"]["Group"][];
            summary: components["schemas"]["Summary"];
            /**
             * Notes
             * @description Izgaranın altındaki açıklama satırları
             */
            notes?: string[];
        };
        /**
         * ShiftHeader
         * @description Gün başlığındaki tek vardiya sayacı: DESIGN §6 'G 6/6' ve 'N 5/5'.
         *
         *     assigned/required YALNIZCA genel mevcut (GENEL slotu), kişi sayısı — saat değil.
         *     Slot kırılımı `slots` içinde, tooltip'e gider; başlık sayacını etkilemez.
         */
        ShiftHeader: {
            /** Code */
            code: string;
            /**
             * Label
             * @enum {string}
             */
            label: "G" | "N";
            /** Assigned */
            assigned: number;
            /** Required */
            required: number;
            /**
             * Slots
             * @description Yalnız sayılabilir görevler: triyaj, gözlem, ambulans
             */
            slots?: components["schemas"]["SlotCoverage"][];
            /**
             * Flags
             * @description Var/yok yetkiler: ekip lideri, sayım yetkilisi
             */
            flags?: components["schemas"]["QualificationFlag"][];
            /**
             * Empty Area
             * @description Ambulans çıkınca boşalan alan adı ('triyaj' / 'gözlem'), yoksa boş
             */
            empty_area?: string | null;
        };
        /** ShiftType */
        ShiftType: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /**
             * Start Time
             * Format: time
             */
            start_time: string;
            /** Duration Hours */
            duration_hours: number;
            /**
             * End Label
             * @description Bitiş saati, insan diliyle
             */
            end_label: string;
            /** Crosses Midnight */
            crosses_midnight: boolean;
            /** Is Active */
            is_active: boolean;
            /** Unit Name */
            unit_name: string;
        };
        /**
         * SlotCoverage
         * @description Bir gün-vardiya içindeki tek slotun durumu. Sütun başlığı tooltip'inde gösterilir.
         */
        SlotCoverage: {
            /** Slot Code */
            slot_code: string;
            /** Label */
            label: string;
            /** Assigned */
            assigned: number;
            /** Required */
            required: number;
        };
        /**
         * SolveAccepted
         * @description POST /solve yanıtı: koşu kaydı açıldı, arka planda çalışıyor.
         */
        SolveAccepted: {
            /** Run Id */
            run_id: number;
            /** Draft Id */
            draft_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "CALISIYOR" | "OPTIMAL" | "FEASIBLE" | "INFEASIBLE" | "HATA";
            /** Poll Url */
            poll_url: string;
            /**
             * Time Limit S
             * @description Arayüz geri sayımı buna göre gösterir
             */
            time_limit_s: number;
        };
        /** SolveRequest */
        SolveRequest: {
            /** Time Limit S */
            time_limit_s?: number | null;
        };
        /**
         * SolverRun
         * @description Bir çözüm koşusu. E-08 metrik tablosu ve durum yoklaması bunu okur.
         */
        SolverRun: {
            /** Id */
            id: number;
            /** Draft Id */
            draft_id: number;
            /**
             * Status
             * @enum {string}
             */
            status: "CALISIYOR" | "OPTIMAL" | "FEASIBLE" | "INFEASIBLE" | "HATA";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Time Limit Seconds */
            time_limit_seconds?: number | null;
            /** Objective Value */
            objective_value?: number | null;
            /**
             * Assignment Count
             * @default 0
             */
            assignment_count: number;
            /**
             * Diagnostic Count
             * @default 0
             */
            diagnostic_count: number;
            /** Elapsed S */
            elapsed_s?: number | null;
            /**
             * Is Reference Copy
             * @description Gerçek çözücü değil, referans haftanın kopyası
             * @default false
             */
            is_reference_copy: boolean;
            /**
             * Status Label
             * @description Arayüzde gösterilecek durum metni
             */
            status_label: string;
            /**
             * Diagnostics Label
             * @description Teşhis listesinin başlığı
             */
            diagnostics_label: string;
        };
        /** Staff */
        Staff: {
            /** Id */
            id: number;
            /**
             * Full Name
             * @description Ad soyad
             */
            full_name: string;
            /** Role Code */
            role_code: string;
            /** Role Name */
            role_name: string;
            /**
             * Shift Eligibility
             * @enum {string}
             */
            shift_eligibility: "gunduz_gece" | "sadece_gunduz" | "sadece_gece";
            /** Is Orientation */
            is_orientation: boolean;
            /** Is Active */
            is_active: boolean;
            /** Seniority Years */
            seniority_years?: number | null;
            /**
             * Buddy Name
             * @description Oryantasyondaysa eşleştiği eğitim hemşiresi
             */
            buddy_name?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Competency Codes
             * @description Tüm yetkinlikler
             */
            competency_codes?: string[];
            /**
             * Task Codes
             * @description Yalnızca görev (kind=TASK) olabilecekler
             */
            task_codes?: string[];
        };
        /**
         * Summary
         * @description DESIGN §6 alt barı.
         */
        Summary: {
            /** Total Hours */
            total_hours: number;
            /** Overtime Hours */
            overtime_hours: number;
            /**
             * Fairness Gap
             * @description Kişiler arası saat farkı: en çok − en az
             */
            fairness_gap: number;
            /**
             * Shortfall Count
             * @description Seçili aralıkta eksik kalan slot sayısı
             */
            shortfall_count: number;
        };
        /** TemplateRow */
        TemplateRow: {
            /** Id */
            id: number;
            /** Shift Code */
            shift_code: string;
            /** Shift Name */
            shift_name: string;
            /** Slot Code */
            slot_code: string;
            /** Slot Label */
            slot_label: string;
            /** Min Count */
            min_count: number;
            /** Competency Codes */
            competency_codes?: string[];
            /** Constraint Code */
            constraint_code?: string | null;
            /** Catalog Code */
            catalog_code?: string | null;
            /** Constraint Name */
            constraint_name?: string | null;
            /** Is Hard */
            is_hard?: boolean | null;
        };
        /** TemplateRowCreate */
        TemplateRowCreate: {
            /**
             * Shift Code
             * @description GUNDUZ / GECE
             */
            shift_code: string;
            /** Slot Code */
            slot_code: string;
            /** Min Count */
            min_count: number;
            /** Competency Codes */
            competency_codes?: string[];
        };
        /** TemplateRowUpdate */
        TemplateRowUpdate: {
            /** Min Count */
            min_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    saglik_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
        };
    };
    listele_api_staff_get: {
        parameters: {
            query?: {
                /** @description Ayrılan personeli gizle */
                sadece_aktif?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getir_api_staff__staff_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Staff"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cizelge_api_drafts__draft_id__schedule_get: {
        parameters: {
            query: {
                /** @description Aralık başlangıcı (dahil) */
                from: string;
                /** @description Aralık bitişi (dahil) */
                to: string;
            };
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hucre_yaz_api_drafts__draft_id__cells_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CellUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listele_api_drafts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"][];
                };
            };
        };
    };
    olustur_api_drafts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getir_api_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taslak_sil_api_drafts__draft_id__delete: {
        parameters: {
            query?: {
                /** @description Yayınlanmış çizelgeyi silmek için açıkça istenmeli */
                force?: boolean;
            };
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coz_api_drafts__draft_id__solve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kosular_api_drafts__draft_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolverRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kosu_api_solver_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolverRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    teshisler_api_solver_runs__run_id__diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticGroup"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taslak_kopyala_api_drafts__draft_id__copy_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DraftCopy"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taslak_yayinla_api_drafts__draft_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draft"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ozet_api_overview_get: {
        parameters: {
            query: {
                from: string;
                /** @description DAHİL — API dışlayıcıya çevirir */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    haftalik_api_demand_get: {
        parameters: {
            query: {
                from: string;
                /** @description DAHİL */
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Demand"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sablon_api_need_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeedTemplate"][];
                };
            };
        };
    };
    satir_sil_api_need_template_rows__row_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                row_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeedTemplate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    satir_guncelle_api_need_template_rows__row_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                row_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateRowUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    satir_ekle_api_need_templates__template_id__rows_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateRowCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NeedTemplate"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listele_api_people_get: {
        parameters: {
            query?: {
                /** @description Ad veya sicilde arama */
                q?: string | null;
                durum?: "aktif" | "pasif" | "hepsi";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    olustur_api_people_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roller_api_people_roles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"][];
                };
            };
        };
    };
    detay_api_people__staff_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sil_api_people__staff_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    guncelle_api_people__staff_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    aktife_al_api_people__staff_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sozlesme_ekle_api_people__staff_id__contracts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    izin_ekle_api_people__staff_id__absences_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbsenceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    izin_sil_api_people__staff_id__absences__absence_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
                absence_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    izin_guncelle_api_people__staff_id__absences__absence_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
                absence_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbsenceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    musaitlik_ekle_api_people__staff_id__availability_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    musaitlik_sil_api_people__staff_id__availability__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    uyumsuzluk_ekle_api_people__staff_id__conflicts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConflictCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    uyumsuzluk_sil_api_people__staff_id__conflicts__other_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
                other_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sozlesme_sil_api_people__staff_id__contracts__contract_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sozlesme_guncelle_api_people__staff_id__contracts__contract_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: number;
                contract_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    yetkinlikler_api_competencies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competency"][];
                };
            };
        };
    };
    matris_api_competency_matrix_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetencyMatrix"];
                };
            };
        };
    };
    yetkinlik_degistir_api_people__staff_id__competencies__code__put: {
        parameters: {
            query: {
                ver: boolean;
            };
            header?: never;
            path: {
                staff_id: number;
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetencyMatrix"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kurallar_api_constraints_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Constraint"][];
                };
            };
        };
    };
    kural_guncelle_api_constraints__constraint_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                constraint_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConstraintUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Constraint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    param_guncelle_api_constraint_params__param_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                param_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParamUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Constraint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vardiyalar_api_shift_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftType"][];
                };
            };
        };
    };
}
